name: "Secrets workflow"
on:
  push:
    branches:
      - main
jobs:
  use_secret:
    runs-on: ubuntu-latest
    steps:
      #- run: echo "This job runs on pull requests"
      - name: Get secrets
        with:
          secrets: ${{ secrets.TEST_SECRET }}